pool:
  vmImage: 'Ubuntu 16.04'

variables:
  acrUrl: $(dockerUser).$(registryDomain)
  imageName: '$(acrUrl)/raiden-events-poller:$(build.buildId)'

steps:
- bash: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'
 
- bash: docker login -u $(dockerUser) -p $(dockerPassword) $(acrUrl)
  displayName: 'docker login'
  
- bash: docker push $(imageName)
  displayName: 'docker push'
